services:
  clojure:
    image: clojure:latest
    env_file: ".env"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    ports:
      - 3030:3000
    entrypoint: >
      sh -c "clojure -M:run-m"
      # sh -c "clojure -X:dev:plus"
      # sh -c "lein repl :headless :host 0.0.0.0 :port 5555"

  redis:
    image: redis:7
    environment:
      TZ: Asia/Toky
    volumes:
      - redis:/data

volumes:
  m2:
    external: true
  gitlibs:
    external: true
  redis:
    driver: local
