services:
  konpy2:
    image: hkim0331/konpy2:0.8.1
    env_file: .env
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    entrypoint: >
      sh -c "java --enable-native-access ALL-UNNAMED -jar konpy2.jar"

  redis:
    image: redis:8
    env_file: .env
    volumes:
      - ./redis:/data
